export default {
  ['zh-CN']: {
    '_settings': {
      rootWidth: '350px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': '基于WebGL2的液态玻璃效果模拟工具',
    'editor.basicSettings': '基础设置',
    'editor.language': '语言',
    'editor.refThickness': '折射厚度',
    'editor.refFactor': '折射系数',
    'editor.refDispersion': '色散增益',
    'editor.refFresnelRange': '菲涅尔反射范围',
    'editor.refFresnelHardness': '菲涅尔反射硬度',
    'editor.refFresnelFactor': '菲涅尔反射强度',
    'editor.glareRange': '高光范围',
    'editor.glareHardness': '高光硬度',
    'editor.glareConvergence': '高光聚拢度',
    'editor.glareOppositeFactor': '高光对侧强度',
    'editor.glareFactor': '高光强度',
    'editor.glareAngle': '高光角度',
    'editor.blurRadius': '模糊半径',
    'editor.blurEdge': '模糊边缘',
    'editor.tint': '色调',
    'editor.shadowExpand': '阴影扩散',
    'editor.shadowFactor': '阴影强度',
    'editor.shadowPosition': '阴影位置',
    'editor.bgType': '背景',
    'editor.shapeSettings': '形状设置',
    'editor.shapeWidth': '宽',
    'editor.shapeHeight': '高',
    'editor.shapeRadius': '圆角 (%)',
    'editor.shapeRoundness': '超椭圆系数',
    'editor.mergeRate': '形状融合度',
    'editor.showShape1': '显示第二个图形',
    'editor.animationSettings': '动画设置',
    'editor.springSizeFactor': '动画形变',
    'editor.debugSettings': '调试',
    'editor.export': '导出预设',
    'editor.import': '导入预设',
    'editor.importSuccessMessage': '预设导入成功！',
    'editor.importFailedMessage': (message: string) => `导入失败：${message}`,
    'editor.copyCSS': '复制 CSS',
    'editor.copyCSSTitle': '复制 Figma CSS',
    'editor.copyCSSSuccess': '已复制到剪贴板！',
    'editor.copyCSSModalTitle': 'Figma CSS 代码',
    'editor.copyCSSModalDesc': '将以下 CSS 复制到 Figma（通过 CSS to Figma 等插件，或作为参考手动应用）',
    'editor.copyCSSModalCopy': '复制',
    'editor.copyCSSModalClose': '关闭',
    'help.button': '?',
    'help.title': '使用指南',
    'help.close': '关闭',
    'help.step1Title': '🎛️ 调整参数',
    'help.step1Desc': '使用左侧面板中的滑块和控件，实时调整液态玻璃效果的各项参数，包括折射、模糊、高光和阴影。',
    'help.step2Title': '🖼️ 切换背景',
    'help.step2Desc': '在"背景"设置中选择不同的背景图像或视频，预览液态玻璃效果在各种场景下的表现。',
    'help.step3Title': '↔️ 调整玻璃大小',
    'help.step3Desc': '拖动画布边缘的把手，可以调整液态玻璃图形的大小。',
    'help.step4Title': '💾 保存与加载预设',
    'help.step4Desc': '点击"导出预设"将当前参数保存为 JSON 文件，点击"导入预设"可重新载入已保存的预设。',
    'help.step5Title': '🎨 复制 Figma CSS',
    'help.step5Desc': '点击"复制 CSS"，将当前液态玻璃效果参数转换为 CSS 代码，方便在 Figma 或其他设计工具中使用。',
  },
  ['en-US']: {
    '_settings': {
      rootWidth: '400px',
      numberInputMinWidth: '42px',
      controlWidth: '215px',
    },
    'ui.subtitle': 'Liquid Glass Effect Simulation Tool based on WebGL2',
    'editor.basicSettings': 'Basic Settings',
    'editor.language': 'Language',
    'editor.refThickness': 'Thickness',
    'editor.refFactor': 'Refraction Factor',
    'editor.refDispersion': 'Dispersion Gain',
    'editor.refFresnelRange': 'Fresnel Size',
    'editor.refFresnelHardness': 'Fresnel Hardness',
    'editor.refFresnelFactor': 'Fresnel Intensity',
    'editor.glareRange': 'Glare Size',
    'editor.glareHardness': 'Glare Hardness',
    'editor.glareConvergence': 'Glare Convergence',
    'editor.glareOppositeFactor': 'Glare Opposite Side',
    'editor.glareFactor': 'Glare Intensity',
    'editor.glareAngle': 'Glare Angle',
    'editor.blurRadius': 'Blur Radius',
    'editor.blurEdge': 'Blur Edge',
    'editor.tint': 'Tint',
    'editor.shadowExpand': 'Shadow Expand',
    'editor.shadowFactor': 'Shadow Intensity',
    'editor.shadowPosition': 'Shadow Position',
    'editor.bgType': 'Background',
    'editor.shapeSettings': 'Shape Settings',
    'editor.shapeWidth': 'Width',
    'editor.shapeHeight': 'Height',
    'editor.shapeRadius': 'Radius (%)',
    'editor.shapeRoundness': 'SuperEllipse Factor',
    'editor.mergeRate': 'Merge Rate',
    'editor.showShape1': 'Show 2nd Shape',
    'editor.animationSettings': 'Animation Settings',
    'editor.springSizeFactor': 'Animation Morph',
    'editor.debugSettings': 'Debug',
    'editor.export': 'Export Preset',
    'editor.import': 'Import Preset',
    'editor.importSuccessMessage': 'Preset imported successfully!',
    'editor.importFailedMessage': (message: string) => `Import failed: ${message}`,
    'editor.copyCSS': 'Copy CSS',
    'editor.copyCSSTitle': 'Copy CSS for Figma',
    'editor.copyCSSSuccess': 'Copied to clipboard!',
    'editor.copyCSSModalTitle': 'Figma CSS',
    'editor.copyCSSModalDesc': 'Copy the CSS below into Figma (via a "CSS to Figma" plugin, or apply manually as a reference)',
    'editor.copyCSSModalCopy': 'Copy',
    'editor.copyCSSModalClose': 'Close',
    'help.button': '?',
    'help.title': 'Quick Guide',
    'help.close': 'Got it',
    'help.step1Title': '🎛️ Tweak the Controls',
    'help.step1Desc': 'Use the panel on the left to adjust refraction, blur, glare, shadow, and shape in real time.',
    'help.step2Title': '🖼️ Change the Background',
    'help.step2Desc': 'Pick a different background image or video under the "Background" setting to see how the effect looks on various content.',
    'help.step3Title': '↔️ Resize the Glass',
    'help.step3Desc': 'Drag the handles on the edges of the canvas to resize the liquid glass shape.',
    'help.step4Title': '💾 Save & Load Presets',
    'help.step4Desc': 'Click "Export Preset" to save your settings as a JSON file, then "Import Preset" to reload them later.',
    'help.step5Title': '🎨 Copy CSS for Figma',
    'help.step5Desc': 'Click "Copy CSS" to get the current effect as CSS code ready to paste into Figma or any other design tool.',
  },
  ['uz-UZ']: {
    '_settings': {
      "rootWidth": "400px",
      "numberInputMinWidth": "42px",
      "controlWidth": "215px"
    },
    "ui.subtitle": "WebGL2 asosidagi Liquid Glass effekt simulyatori",
    "editor.basicSettings": "Asosiy sozlamalar",
    "editor.language": "Til",
    "editor.refThickness": "Qalinlik",
    "editor.refFactor": "Sinish koeffitsiyenti",
    "editor.refDispersion": "Dispersiya darajasi",
    "editor.refFresnelRange": "Fresnel o‘lchami",
    "editor.refFresnelHardness": "Fresnel qattiqligi",
    "editor.refFresnelFactor": "Fresnel intensivligi",
    "editor.glareRange": "Yaltiroq maydoni",
    "editor.glareHardness": "Yaltiroq qattiqligi",
    "editor.glareConvergence": "Yaltiroq to‘planishi",
    "editor.glareOppositeFactor": "Qarama-qarshi tomon yorqinligi",
    "editor.glareFactor": "Yaltiroq intensivligi",
    "editor.glareAngle": "Yaltiroq burchagi",
    "editor.blurRadius": "Xiralashish radiusi",
    "editor.blurEdge": "Xiralashish qirralar",
    "editor.tint": "Rang ohangi",
    "editor.shadowExpand": "Soya kengligi",
    "editor.shadowFactor": "Soya kuchi",
    "editor.shadowPosition": "Soya joylashuvi",
    "editor.bgType": "Fon turi",
    "editor.shapeSettings": "Shakl sozlamalari",
    "editor.shapeWidth": "Kenglik",
    "editor.shapeHeight": "Balandlik",
    "editor.shapeRadius": "Radius (%)",
    "editor.shapeRoundness": "Burchak yumaloqligi",
    "editor.mergeRate": "Qo‘shilish tezligi",
    "editor.showShape1": "2-shaklni ko‘rsatish",
    "editor.animationSettings": "Animatsiya sozlamalari",
    "editor.springSizeFactor": "Animatsiya deformatsiyasi",
    "editor.debugSettings": "Debug",
    "editor.export": "Presetni eksport qilish",
    "editor.import": "Presetni import qilish",
    "editor.importSuccessMessage": "Preset muvaffaqiyatli import qilindi!",
    "editor.importFailedMessage": (message: string) => `Import failed: ${message}`,
    "editor.copyCSS": "CSS nusxalash",
    "editor.copyCSSTitle": "Figma uchun CSS nusxalash",
    "editor.copyCSSSuccess": "Buferga nusxalandi!",
    "editor.copyCSSModalTitle": "Figma CSS",
    "editor.copyCSSModalDesc": "Quyidagi CSS-ni Figma-ga ko'chiring (\"CSS to Figma\" plagini orqali yoki qo'lda qo'llang)",
    "editor.copyCSSModalCopy": "Nusxalash",
    "editor.copyCSSModalClose": "Yopish",
    "help.button": "?",
    "help.title": "Qo'llanma",
    "help.close": "Tushunarli",
    "help.step1Title": "🎛️ Sozlamalarni o'zgartiring",
    "help.step1Desc": "Sinish, xiralashish, yaltiroq, soya va shakl parametrlarini chap paneldagi boshqaruvlar orqali real vaqtda o'zgartiring.",
    "help.step2Title": "🖼️ Fonni almashtiring",
    "help.step2Desc": "\"Fon turi\" sozlamasidan boshqa rasm yoki videoni tanlang va liquid glass effekti turli kontentda qanday ko'rinishini ko'ring.",
    "help.step3Title": "↔️ Shisha hajmini o'zgartiring",
    "help.step3Desc": "Canvas chekkasidagi tutqichlarni tortib liquid glass shaklini katta-kichik qiling.",
    "help.step4Title": "💾 Presetlarni saqlash va yuklash",
    "help.step4Desc": "\"Presetni eksport qilish\" tugmasi joriy sozlamalarni JSON faylga saqlaydi; \"Presetni import qilish\" esa ularni qayta yuklaydi.",
    "help.step5Title": "🎨 Figma uchun CSS nusxalash",
    "help.step5Desc": "\"CSS nusxalash\" tugmasini bosib, joriy effektni CSS kodiga aylantirib oling va Figma yoki boshqa dizayn vositalariga joylashtiring.",
  }
}
