import { type useLevaControls } from '../Controls';
export interface PresetData {
  version: string;
  timestamp: string;
  controls: ReturnType<typeof useLevaControls>['controls'];
}

export function generateCSSForFigma(
  controls: ReturnType<typeof useLevaControls>['controls'],
): string {
  const {
    shapeWidth,
    shapeHeight,
    shapeRadius,
    blurRadius,
    tint,
    shadowExpand,
    shadowFactor,
    shadowPosition,
    refFresnelFactor,
    refFresnelRange,
    glareFactor,
  } = controls;

  // Compute actual border radius in pixels
  const radiusPx = Math.round(((Math.min(shapeWidth, shapeHeight) / 2) * shapeRadius) / 100);

  // Blur
  const blur = Math.round(blurRadius);

  // Tint
  const tintAlpha = Math.round(tint.a * 100);
  const tintRgba = `rgba(${tint.r}, ${tint.g}, ${tint.b}, ${tint.a.toFixed(2)})`;

  // Shadow (controls.shadowFactor is 0-100, shadowExpand is 2-100)
  const shadowAlpha = ((shadowFactor / 100) * 0.6).toFixed(2);
  const shadowBlur = Math.round(shadowExpand * 2);
  const shadowX = Math.round(-shadowPosition.x);
  const shadowY = Math.round(-shadowPosition.y);

  // Fresnel border glow
  const fresnelOpacity = ((refFresnelFactor / 100) * 0.5).toFixed(2);
  const fresnelBlur = Math.round(refFresnelRange * 0.6);
  const fresnelOpacityHighlight = Math.min(parseFloat(fresnelOpacity) * 1.5, 1).toFixed(2);

  // Glare (glareFactor is 0-120)
  const glareOpacity = ((glareFactor / 120) * 0.25).toFixed(2);

  const hasDropShadow = shadowFactor > 0;
  const hasTint = tint.a > 0;

  const lines: string[] = [
    '/* Liquid Glass CSS — Figma approximation */',
    '/* Generated by Liquid Glass Studio       */',
    '',
    '.liquid-glass {',
    `  width: ${shapeWidth}px;`,
    `  height: ${shapeHeight}px;`,
    `  border-radius: ${radiusPx}px;`,
    '',
    `  /* Background blur — Figma: Add > Background Blur, value ${blur} */`,
    `  backdrop-filter: blur(${blur}px) saturate(180%);`,
    `  -webkit-backdrop-filter: blur(${blur}px) saturate(180%);`,
    '',
  ];

  if (hasTint) {
    lines.push(`  /* Tint — Figma: Add Fill, opacity ${tintAlpha}% */`);
    lines.push(`  background: ${tintRgba};`);
  } else {
    lines.push('  background: transparent;');
  }

  lines.push('');
  lines.push('  /* Glare highlight — Figma: Add Fill with Angle Gradient */');
  lines.push(
    `  /* gradient from rgba(255,255,255,${glareOpacity}) to transparent at angle ${controls.glareAngle}deg */`,
  );

  const shadowParts: string[] = [];
  if (hasDropShadow) {
    shadowParts.push(
      `    ${shadowX}px ${shadowY}px ${shadowBlur}px rgba(0, 0, 0, ${shadowAlpha})`,
    );
  }
  shadowParts.push(
    `    inset 0 0 ${fresnelBlur}px rgba(255, 255, 255, ${fresnelOpacity})`,
  );
  shadowParts.push(
    `    inset 0 1px 1px rgba(255, 255, 255, ${fresnelOpacityHighlight})`,
  );

  const shadowValue = shadowParts
    .map((part, i) => (i < shadowParts.length - 1 ? `${part},` : `${part};`))
    .join('\n');

  lines.push('');
  lines.push(`  /* box-shadow — Figma: Add Drop Shadow / Inner Shadow */`);
  lines.push('  box-shadow:');
  lines.push(shadowValue);
  lines.push('}');

  return lines.join('\n');
}

export function exportPreset(
  controls: ReturnType<typeof useLevaControls>['controls'],
  filename: string = 'liquid-glass-preset.json',
): void {
  const preset: PresetData = {
    version: '1.0.0',
    timestamp: new Date().toISOString(),
    controls: structuredClone(controls),
  };

  const jsonStr = JSON.stringify(preset, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function importPreset(file: File): Promise<PresetData> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const preset = JSON.parse(content) as PresetData;

        if (!preset.version || !preset.controls) {
          reject(new Error('Invalid preset file format'));
          return;
        }

        resolve(preset);
      } catch (err) {
        reject(new Error(`Failed to parse preset file: ${err}`));
      }
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsText(file);
  });
}
